### PR TITLE
fix: remove useNavigation hook from SignInForm to support current rou…

### LINKED ISSUE #42: Implement React Toast Notification for Account Creation and Login Success
**Description:**
- Display toast notifications after successful account creation and login
- Use a toast library `react-hot-toast`
- Trigger the notifications inside `useSignUp` and `useLogin` hooks after successful API mutation

**Proposed Actions:**

1. **Fork and Create a Branch**
   ```bash
   git checkout -b feat/auth-toast-notifications
   ```

2. **Implement Changes**
- Install a toast library:
```bash
npm install react-hot-toast
```
- Add the Toast provider to your root layout
- Use `toast.success()` inside `useSignUp` and `useLogin` hooks

**Sample messages:**
- "Account created successfully!"
- "Login successful, welcome back!

3. **Test & Commit**
- Test that the toast shows up on success
- Ensure no blocking UI behavior

Commit with:
```bash
git commit -m "feat: add toast notifications for signup and login success"
```

### PR DESCRIPTION
**Pull request by Nishantsingh11**
## Description  

Added authentication pages (`SignInForm`, `SignUpForm`) and integrated them properly with react-router-dom. Fixed routing issues by ensuring components use the appropriate hooks and structure compatible with BrowserRouter.
## Related Issues  

close #42

## Changes Made  
- Implemented `SignInForm` and `SignUpForm` components.
- Integrated `useForm` with `yupResolver` for form validation.
- Set up `LandingLayout` and `AuthLayout`.
- Configured routes for landing pages and auth pages.
- Added `QueryClientProvider` for React Query to prevent missing QueryClient error.
- Updated React Router to use correct layout structure.

## How to Test  

1. Pull the latest code.
2. Run `npm install` to install any missing dependencies.
3. Start the app with `npm run dev`.
4. Navigate to `/signin` and `/signup` pages.
5. Test form validation by trying to submit empty forms.
6. Check routing between landing and auth pages.

## Screenshots (if applicable)  

[Screencast From 2025-04-26 12-52-47.webm](https://github.com/user-attachments/assets/e9195cc3-6b2b-4e9e-bc73-975828eba49d)

## Checklist  
- [x] My code follows the project's coding style.
- [x] I have tested these changes locally.
- [ ] Documentation has been updated where necessary.

### CODE REVIEW

**Comment by Nishantsingh11** [comment]
Hey @BigBen-7 can you please check

File: src/hooks/useForgotPassword.js [hunk 1]
```diff
@@ -0,0 +1,32 @@
...
+    setError(null);
+    
+    try {
+      // Call your API endpoint for forgot password
+      // const response = await authApi.forgotPassword(email);
+      
+      // Simulate API call
+      await new Promise(resolve => setTimeout(resolve, 1500));
+      
+      toast.success('Password reset link sent to your email.');
```
Comment (BigBen-7) [inline src/hooks/useForgotPassword.js:20]: change the 'Password reset link set to your email" to 'Email successfully sent'
and it should only display when a user is in the forgot password page not on login.

**Review by BigBen-7 — COMMENTED** [review]
@Nishantsingh11 Good work, fix this review and we are good to go.

**Comment by Nishantsingh11** [comment]
@BigBen-7 check again please

**Review by BigBen-7 — APPROVED** [review]
